Container
stxinsite/CDD_compound_registration_DegraderStudio pull request #1
Opened 2022-09-21 21:08 UTC by li-songlu

The container is ready on NEO. I am working with DegraderStudio to standardize the sdf/csv format.

2022-09-22 19:55 UTC, jsiegel-roivant requested changes
This looks good.  I have one main comment, which repeats throughout, which is that we should probably change the filenames and container names to ensure they are different than the version of this tool that was build for D2Bvant / Psivant.  The biggest concern I have is that this might overwrite their container.

2022-09-22 19:55 UTC, jsiegel-roivant commented on .circleci/config.yml
> +          command: "srun -N 1 -n 1 -c 8 -p debug --qos restrained --account=jenkins bash -c \"mkdir /scratch/\\$SLURM_JOB_ID && export SINGULARITY_TMPDIR=/scratch/\\$SLURM_JOB_ID && singularity build
I think we need to change the name of the container.  Isn't this the same as the container for D2BVant's tool?  I think that this would overwrite their tool because it copies the code into the container, right?

2022-09-22 19:55 UTC, jsiegel-roivant commented on .circleci/config.yml
> +            singularity --debug push ./CDD_API_compound_reg.sif oras://ghcr.io/stxinsite/cdd-data-upload:$CIRCLE_BRANCH
similar to above.  I think we need to change it here, too.  Something like `CDD_API_compound_reg_dynamite` would work.

2022-09-22 19:55 UTC, jsiegel-roivant commented on .circleci/config.yml
> +            mkdir -p /projects2/common/CDD_API_compound_reg_degraderstudio/$CIRCLE_BRANCH && rsync CDD_API_compound_reg.sif /projects2/common/CDD_API_compound_reg_degraderstudio/$CIRCLE_BRANCH/CDD_AP
same comment as above.

2022-09-22 19:55 UTC, jsiegel-roivant commented on .circleci/config.yml
> +      - build-cdd-compound-registration
and probably best to change the name of the job here and at line 6, as well, don't you think?

2022-09-22 19:55 UTC, jsiegel-roivant commented on CDD_API_compound_reg.def
> +  python /CDD_API_scripts/CDD_compound_reg.py "$@"
I think for clarity, I would suggest changing the filename of `CDD_compound_reg.py` to `CDD_compound_reg_dynamite.py`

2022-09-22 19:55 UTC, jsiegel-roivant commented on CDD_API_scripts/CDD_compound_reg.py
> +    project_list = ['PLT_BRD4', 'PLT_KRAS_Degrader', 'PLT_SMARCA2', 'TEST']
Other than the previous suggestion to change the filename (`CDD_compound_reg.py` -> `CDD_compound_reg_dynamite.py`) this looks good.

2022-09-22 19:55 UTC, jsiegel-roivant commented on CDD_API_scripts/design_set_001.csv
> +Smiles,SiTX,Batch
do we want to include this file and `design_set_001.sdf` in the `.gitignore` or is intended to be a test case for future updates?

2022-09-22 19:55 UTC, jsiegel-roivant commented on CDD_API_scripts/util.py
> +    params = SmilesWriteParams()
It would be nice to add a docstring giving Alex Liholips credit for coming up with the standardization functions.  Something like ` standardization methodology curtesy of Alex Liholips`

2022-09-22 19:55 UTC, jsiegel-roivant commented on README.md
> +Build: singularity build --fakeroot CDD_API_compound_reg.sif CDD_API_compound_reg.def
As is the main comment, I'd just adjust the filenames to ensure they are different than the tool that you built for D2Bvant / Psivant.

2022-09-22 20:02 UTC, li-songlu commented on .circleci/config.yml
> +            mkdir -p /projects2/common/CDD_API_compound_reg_degraderstudio/$CIRCLE_BRANCH && rsync CDD_API_compound_reg.sif /projects2/common/CDD_API_compound_reg_degraderstudio/$CIRCLE_BRANCH/CDD_AP
I think this step copy the code to the path that I created. I make it as /projects2/common/CDD_API_compound_reg_degraderstudio/$CIRCLE_BRANCH instead of /projects2/common/CDD_API_compound_reg/$CIRCLE_BRANCH. 

It won't affect the Psivant tool. I just tested it.

2022-09-22 20:05 UTC, li-songlu commented on CDD_API_scripts/util.py
> +    params = SmilesWriteParams()
Thank you so much for the suggestion! I will add Alex's contribution to the docstring.

2022-09-23 14:38 UTC, li-songlu commented on CDD_API_scripts/design_set_001.csv
> +Smiles,SiTX,Batch
I deleted the csv output. The sdf is a test case.

2022-09-23 14:41 UTC, li-songlu commented on CDD_API_compound_reg.def
> +  python /CDD_API_scripts/CDD_compound_reg.py "$@"
Just had the main function script name changed.

2022-09-23 19:27 UTC, jsiegel-roivant approved these changes
Looks good!  Thanks for making the clarifying changes!

2022-09-23 19:28 UTC, merged